# Generated by Django 4.2.7 on 2023-12-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('DF', 'DRAFT'), ('PB', 'Published')], default='DF', max_length=2),
        ),
    ]
